# Generated by Django 4.2.4 on 2023-08-09 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.services.upload_image_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0006_remove_postmodel_brand_remove_postmodel_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=core.services.upload_image_service.upload_image)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'Bmw'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('ВАЗ / Lada', 'Vaz Lada')], max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 25 ch')])),
                ('model', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1935), django.core.validators.MaxValueValidator(2023)])),
                ('images', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.imagemodel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='posts.postmodel')),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('id',),
            },
        ),
    ]
