# Generated by Django 4.2.4 on 2023-08-09 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postmodel_brand_remove_postmodel_images_and_more'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'Bmw'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('ВАЗ / Lada', 'Vaz Lada')], max_length=25, validators=[django.core.validators.RegexValidator('^[А-ЯЁІЇЄҐ][А-яёЁіІєЄїЇґҐ]{1,49}|[A-Z][a-zA-Z\\d]{1,49}$', 'First letter uppercase min 2 max 25 ch')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='posts.postmodel'),
        ),
    ]
