# Generated by Django 4.2.4 on 2023-08-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postmodel_brand_remove_postmodel_images_and_more'),
        ('cars', '0004_remove_carmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='posts.postmodel'),
            preserve_default=False,
        ),
    ]
