# Generated by Django 4.2.4 on 2023-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_phone_alter_profilemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
