# Generated by Django 4.2.4 on 2023-08-08 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.services.upload_image_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=core.services.upload_image_service.upload_image)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField()),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'Bmw'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes - Benz', 'Mercedes Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('ВАЗ / Lada', 'Vaz Lada')], max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 25 ch')])),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1935), django.core.validators.MaxValueValidator(2023)])),
                ('region', models.CharField(choices=[('Вінницька', 'Vinnytsia'), ('Волинська', 'Volyn'), ('Дніпропетровська', 'Dnipropetrovsk'), ('Донецька', 'Donetsk'), ('Житомирська', 'Zhytomyr'), ('Закарпатська', 'Zakarpattia'), ('Запорізька', 'Zaporizhia'), ('Івано - Франківська', 'Ivano Frankivsk'), ('Київська', 'Kyiv'), ('Кіровоградська', 'Kirovohrad'), ('Луганська', 'Luhansk'), ('Львівська', 'Lviv'), ('Миколаївська', 'Mykolaiv'), ('Одеська', 'Odessa'), ('Полтавська', 'Poltava'), ('Рівненська', 'Rivne'), ('Сумська', 'Sumy'), ('Тернопільська', 'Ternopil'), ('Харківська', 'Kharkiv'), ('Херсонська', 'Kherson'), ('Хмельницька', 'Khmelnytskyi'), ('Черкаська', 'Cherkasy'), ('Чернівецька', 'Chernivtsi'), ('Чернігівська', 'Chernihiv')], max_length=19)),
                ('descriptions', models.CharField(blank=True, max_length=255)),
                ('images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.imagemodel')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ('id',),
            },
        ),
    ]
