# Generated by Django 4.2.4 on 2023-08-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodel_active_status_alter_postmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='images',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.imagemodel'),
        ),
    ]
