# Generated by Django 4.2.4 on 2023-08-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postmodel_views_count_alter_postmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='year',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
